### ISSUE TITLE
V3 migration checklist

### ISSUE THREAD

**Issue by bdon** [protomaps/PMTiles#80]
- [x] Python `pmtiles-convert` writes v3 (show notice about migrating to go-pmtiles)
- [x] Python library reads v3
- [x] `go-pmtiles` serves, shows, reads v3
- [x] `go-pmtiles` has version 2 to version 3 conversion utility
- [x] `go-pmtiles` has easy binary installation for multiple platforms
- [x] AWS Lambda reads v3
- [x] Cloudflare Workers reads v3
